<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SudokuGen.Tui</RootNamespace>
    <AssemblyName>sudoku-tui</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Terminal.Gui" />
    <ProjectReference Include="..\..\core\SudokuGen.csproj" />
    <InternalsVisibleTo Include="SudokuGen.Tests" />
  </ItemGroup>

</Project>
